[package]
name = "err_handling"
version = "0.1.0"
authors = ["k1r1m1 <matthewscurtis.dev81@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
